version: 2
jobs:
  build:
    docker: # An executor, defines the underlying technology or environment in which to run a job
      - image: cimg/python:3.9.2
    steps:
      # Without the checkout step, CircleCI doesn't have your code. Without the code,
      # it can't do anything that it's suppose to do. For example,
      # CircleCI won't be able to run your tests, compile your code, or deploy your code.
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest
            
  deploy:
    docker:
      # buildpack-deps
      # A collection of common build dependencies used for installing various modules
      - image: circleci/buildpack-deps:stretch # Extends the official image of buildpack-deps for better use on CircleCI.
    steps:
      - checkout

      # To build Docker images for deployment, you must use a special setup_remote_docker
      # key which creates a separate environment for each build for security. This environment is
      # remote, fully-isolated and has been configured to execute Docker commands. If your job
      # requires docker or docker-compose commands, add the setup_remote_docker step into your
      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build and push to Docker Hub
          command: |
            docker build -t $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest . 
            echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER_ID" --password-stdin
            docker push $DOCKER_HUB_USER_ID/$IMAGE_NAME:latest


workflows:
  version: 2
  build-master:
    jobs:
      - build
      - deploy:
          requires:
            - build
